title: Xuechun (Leonie) Lu # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Leonie! I'm a MMath candidate in Statistics from University of Waterloo!
  <br><br>
  I'm a statistics nerd and super passionate about data science!
  <br><br>
  My life motto is: "一生懸命"  (to the best of one's ability, to try one's utmost hardest)!
  <br><br>
  <a href="https://www.linkedin.com/in/xuechun-lu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
